
disabled_rules:
 - trailing_whitespace
 - identifier_name
 - closure_parameter_position
 - control_statement
 - unused_optional_binding
 - unneeded_break_in_switch
 - force_cast
 - cyclomatic_complexity
 - void_return
 - function_body_length
line_length: 250

vertical_whitespace:
    max_empty_lines: 2
 
